import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProviderWrapper } from "@/context/ThemeContext/ThemeContext";
import type { Metadata } from "next";
import { FilterProviderWrapper } from "@/context/FilterContext/FilterContext";

export const metadata: Metadata = {
  title: "Movie List",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FilterProviderWrapper>
          <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
        </FilterProviderWrapper>
      </body>
    </html>
  );
}
